const { Pool } = require('pg');
const path = require('path');
const dotenv = require('dotenv');
dotenv.config({ path: path.join(__dirname, '..', '.env') });
const dbConfig = require('../db.config');

async function run() {
  let pool = new Pool(dbConfig);
  try {
    try {
      await pool.query('SELECT 1');
      console.log('Connected to PostgreSQL successfully (db.config)');
    } catch (err) {
      console.warn('Primary connection failed:', err && err.message ? err.message : err);
      console.warn('Attempting fallback to local connection string without explicit credentials');
      try {
        pool = new Pool({ connectionString: 'postgresql://localhost/imtse_portal' });
        await pool.query('SELECT 1');
        console.log('Connected to PostgreSQL successfully (fallback connectionString)');
      } catch (err2) {
        console.error('Fallback connection failed:', err2 && err2.message ? err2.message : err2);
        await pool.end().catch(()=>{});
        process.exit(1);
      }
    }

    // Create students table
    await pool.query(`
      CREATE TABLE IF NOT EXISTS students (
        reg_no VARCHAR(50) NOT NULL,
        full_name VARCHAR(255) NOT NULL,
        student_class VARCHAR(20) NOT NULL,
        medium VARCHAR(50) NOT NULL,
        school_name VARCHAR(255) NOT NULL,
        dob DATE NOT NULL,
        parent_name VARCHAR(255) NOT NULL,
        whatsapp VARCHAR(20) NOT NULL,
        email VARCHAR(255),
        address TEXT NOT NULL,
        amount VARCHAR(50) NOT NULL,
        pay_mode VARCHAR(100) NOT NULL,
        payment_screenshot_name VARCHAR(255),
        payment_screenshot_data TEXT,
        status VARCHAR(100) NOT NULL DEFAULT 'Pending Verification',
        reg_date DATE NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (whatsapp)
      );
    `);

    // Ensure unique constraint on reg_no
    await pool.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM pg_constraint c
          JOIN pg_class t ON c.conrelid = t.oid
          WHERE c.contype = 'u' AND t.relname = 'students' AND c.conname = 'uniq_reg_no'
        ) THEN
          ALTER TABLE students ADD CONSTRAINT uniq_reg_no UNIQUE (reg_no);
        END IF;
      END$$;
    `);

    // Create admin_users table
    await pool.query(`
      CREATE TABLE IF NOT EXISTS admin_users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username VARCHAR(50) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    `);

    // Insert default admin user (idempotent)
    await pool.query(`
      INSERT INTO admin_users (username, password)
      VALUES ('admin', 'admin')
      ON CONFLICT (username) DO UPDATE SET password = EXCLUDED.password;
    `);

    // Create study_resources table
    await pool.query(`
      CREATE TABLE IF NOT EXISTS study_resources (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        category VARCHAR(50) NOT NULL,
        resource_type VARCHAR(20) NOT NULL,
        url VARCHAR(1000),
        description TEXT,
        file_name VARCHAR(255),
        file_data TEXT,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    `);

    // Report created tables
    const res = await pool.query(`
      SELECT table_name FROM information_schema.tables
      WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
      ORDER BY table_name;
    `);

    console.log('Existing tables:');
    res.rows.forEach(r => console.log(' -', r.table_name));

    // Also report row counts for each created table
    for (const row of res.rows) {
      const t = row.table_name;
      try {
        const c = await pool.query(`SELECT COUNT(*)::bigint AS cnt FROM "${t}"`);
        console.log(`COUNT:${t}:${c.rows[0].cnt}`);
      } catch (countErr) {
        console.warn(`COUNT:${t}:ERROR:${countErr && countErr.message ? countErr.message : countErr}`);
      }
    }

    await pool.end();
    console.log('Schema initialization complete');
  } catch (err) {
    console.error('Initialization failed:', err && err.message ? err.message : err);
    try { await pool.end(); } catch {};
    process.exit(1);
  }
}

run();
